max_idle_timeout = 0
max_handshake_timeout = 30
max_concurrent_conns = 1000000
recv_udp_payload_size = 65527
send_udp_payload_size = 1200
initial_max_data = 10485760
initial_max_stream_data_bidi_local = 5242880
initial_max_stream_data_bidi_remote = 2097152
initial_max_stream_data_uni = 1048576
initial_max_streams_bidi = 200
initial_max_streams_uni = 100
cc_algorithm = "bbr"
