[package]
name = "vauid"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true

axum = { version = "0.8.9", features = ["ws"] }
tokio = { version = "1.52.3", features = ["full"] }
vauid-shared = { path = "../vauid-shared" }
str0m = "0.22.0"
tracing = "0.1.44"
dashmap = "6.1.0"
uuid = { version = "1.18.1", features = ["v4"] }
futures-util = "0.3.31"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tquic = "1.6.0"
slab = "0.4.12"

[dev-dependencies]
tokio-tungstenite = "0.29.0"
